### ISSUE TITLE
Admin: Voting booth setup

### ISSUE THREAD

**Issue by adzialocha** [lazaruslabs/culturestake#25]
#### Description

* Admins can go to the url `/booth` it checks if an voting booth keypair exists, if not it automatically generates and stores a new keypair in the LocalStorage. If a keypair already exists it just redirects to the existing one.
* The `/booth` view checks frequently if the booth got activated, if not it shows a QR code of the public address, if yes it shows the voting booth UI
* The keypair can be burned clicking a Button somewhere :star2: 

#### Smart Contract

Source: https://github.com/lazaruslabs/culturestake-contracts/blob/master/contracts/Culturestake.sol

* `function initVotingBooth(bytes32 _festival, address _booth) public authorized`
* `function deactivateVotingBooth(address _booth) public authorized`

#### Todo

Path: `/booth`

* [x] Checks if a keypair exists and automatically redirects to the according view, if not if will generate one first
* [x] Check in the background if booth is activated
* [x] Fetches the related artworks of the festival (connected through questions -> answers)
* [x] Gives an option to burn the keypair
* [x] Creates a vote (see Vote Session flow)

Vote Session flow:

1. Wait for all barcodes of visitor to be scanned, the booth maintainer can also click "Manual override" and activate / deactivate artworks
2. Finish by clicking "Done scanning" button
3. Voting booth signs answers + nonce which can be voted upon
4. View shows a QR code containing `nonce`, `answerIds[]`, `signature` and `questionAddress`
5. Visitor can scan QR code to go on with vote on their device or choose to vote on booth device

Path: `/admin/festivals/:slug/edit`

* [x] Show a list of voting booths via the graph
* [x] Have a form which calls `initVotingBooth`
* [x] Button to deactivate booths

#### Related issues

* https://github.com/lazaruslabs/culturestake/issues/32

**Comment by adzialocha** [comment]
@ana0 There are some admin tasks left, fyi
