### ISSUE TITLE
Admin: Manage festivals

### ISSUE THREAD

**Issue by adzialocha** [lazaruslabs/culturestake#26]
#### Description

* Owners can register new festivals in the `CultureStake` contract instance
* A list of festivals can be retreived from the Graph

#### Smart Contract

Source: https://github.com/lazaruslabs/culturestake-contracts/blob/master/contracts/Culturestake.sol

* `function initFestival(bytes32 _festival, uint256 _duration) public authorized`
* `function deactivateFestival(bytes32 _festival) public authorized`
* `function getFestival(bytes32 _festival) public view returns (bool, uint256, uint256)`
* `function isValidFestival(bytes32 _festival) public view returns (bool)`

#### Todo

Path: `/admin/festivals/:slug/edit`

* [x] Create a festival instance (off-chain) in the database, introduce `chainId`, `startDate`, `endDate` in model, make sure they are set (https://github.com/lazaruslabs/culturestake/issues/30)
* [x] Call `getFestival` when entering a festival view to check if it is initialized (related: https://github.com/lazaruslabs/culturestake/issues/29)
* [x] Give an option to call `initFestival` if it is not initialized yet
* [x] Give an option to call `deactivateFestival` if it is already initialized (This is a destructive action :warning:)

#### Related issues

* https://github.com/lazaruslabs/culturestake-contracts/issues/12

**Comment by ana0** [comment]
First point is done, but I removed `startDate`, and `endDate` from the model, since they're in the contracts and I wasn't sure we needed to duplicate
