### ISSUE TITLE
Admin: Question / Answer management

### ISSUE THREAD

**Issue by adzialocha** [lazaruslabs/culturestake#31]
#### Description

* Owners of the `CultureStake` smart contract can add / remove questions to festivals and attach multiple answers to them
* The questions related to a festival can be retreived from the Graph
* The answers related to a question can be retreived from the Graph

#### Smart Contract

Source: https://github.com/lazaruslabs/culturestake-contracts/blob/master/contracts/Culturestake.sol

* `function initQuestion(uint8 _questionType, bytes32 _question, uint256 _maxVoteTokens, bytes32 _festival) public authorized`
* `function deactivateQuestion(address _question) public authorized`
* `event InitQuestion(address questionAddress, uint8 questionType, bytes32 question)`

Source:  https://github.com/lazaruslabs/culturestake-contracts/blob/master/contracts/Question.sol

* `function initAnswer(bytes32 _answer) public authorized`
* `function deactivateAnswer(bytes32 _answer) public authorized`
* `function getAnswer(bytes32 _answer) public returns (bool, uint256, uint256, uint256)`
* `event InitAnswer(bytes32 answer)`

#### Todo

Path: `/admin/festivals/:slug/questions`

* [x] Fetch all questions related to the festival and render them into a table
* [x] Show a button to create a new question

Path: `/admin/festivals/:slug/questions/new`

* [x] Form for creating a new question (title, maxVoteTokens can be set)
* [x] Calls `initQuestion` and checks for the created address, a) deploy Contract b) retreive address from created contract c) call API to create question (define type and optionally which artwork is attached to it)

Path: `/admin/festivals/:slug/questions/:questionSlug/edit`

* [x] Form for creating a new question (title, maxVoteTokens can be set)
* [x] Show a button to deactivate the question (destructive action :warning: )
* [x] Show all answers related to the question and render them into a table
* [x] Calls `initAnswer` flow: a) call API to create answer b) retreive `chainId` from created answer c) call `initAnswer` method on contract
* [x] Show a button to deactivate the answer (destructive action :warning: )
* [x] Support artwork-questions
* [x] For festival-questions, use `defaultQuery` in Finder to only search artworks from that festival
* [x] Change the create answer page to reflect whether it's a festival-question or artwork-question

#### Related issues

* https://github.com/lazaruslabs/culturestake-contracts/issues/11
